---
abstract: 'require() modules from a variable'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UNIVERSAL-require
no_index:
  directory:
    - t
    - inc
  package:
    - UNIVERSAL
requires:
  Carp: 0
  Test::More: 0.47
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/neilbowers/UNIVERSAL-require.git
version: 0.17
