---
abstract: 'require() modules from a variable'
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UNIVERSAL-require
no_index:
  directory:
    - t
    - inc
  package:
    - UNIVERSAL
requires:
  Test::More: 0.47
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=UNIVERSAL-require
  license: http://dev.perl.org/licenses/
  repository: https://github.com/neilbowers/UNIVERSAL-require
version: 0.13_1
